homework-8/hw8-problem1-app/config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  devise_for :users

  root "home#index"

  resources :users
end

homework-8/hw8-problem1-app/app/models/hotel.rb
class Hotel < ActiveRecord::Base


  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
end

homework-8/hw8-problem1-app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :headline, presence: true
  validates :profile, presence: true
end

homework-8/hw8-problem1-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

homework-8/hw8-problem1-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

homework-8/hw8-problem1-app/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    set_hotel
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.fetch(:hotel, {}).permit(:name, :location, :description)
    end
end

homework-8/hw8-problem1-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action(:authenticate_user!, only: [:index, :show, :edit])

  def index
    @users = User.all
  end

  def show
    get_user
  end

  def edit
    get_user
    # if current_user.admin? ||  current_user.id == @user.id
    #   get_user
    # else
    #   redirect_to(action: :index )
    # end
  end

  def update
    get_user
    @user.update(user_params)
    redirect_to_user_if_valid(:edit, 'User was sucessfully updated!', 'There was an error')
  end


  private

  def redirect_to_user_if_valid(action_to_render, success_copy, failure_copy)
    if @user.valid?
      flash.notice = success_copy
      redirect_to(@user)
    else
      flash.now.alert = failure_copy
      render(action_to_render)
    end
  end

  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user].permit(:email, :name, :headline, :profile, :admin)
  end
end

homework-8/hw8-problem1-app/app/helpers/application_helper.rb
module ApplicationHelper
end

homework-8/hw8-problem1-app/app/helpers/home_helper.rb
module HomeHelper
end

homework-8/hw8-problem1-app/app/helpers/hotels_helper.rb
module HotelsHelper
end

homework-8/hw8-problem1-app/app/helpers/users_helper.rb
module UsersHelper
end

homework-8/hw8-problem1-app/app/views/home/index.html.erb
<h1>Welcome to the Homework 7 Problem 1 App</h1>

homework-8/hw8-problem1-app/app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label(:name) %>:
    <%= f.text_field(:name) %>
  </p>

  <p>
    <%= f.label(:description) %>:
    <%= f.text_field(:description) %>
  </p>

  <p>
    <%= f.label(:location) %>:
    <%= f.text_field(:location) %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

homework-8/hw8-problem1-app/app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

homework-8/hw8-problem1-app/app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hotels</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %> |</td>
        <td><%= hotel.description %> |</td>
        <td><%= hotel.location %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

homework-8/hw8-problem1-app/app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

homework-8/hw8-problem1-app/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @hotel.name %></p>
<p><%= @hotel.description %></p>
<p><%= @hotel.location %></p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

homework-8/hw8-problem1-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw7Problem1App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <p> <a> <%= link_to("All Users", users_path) %> </a></p>

    <% if user_signed_in?%>
      <p>You are logged in as <%= current_user.email %></p>
      <p><%= link_to('My Profile', current_user) %></p>
      <p><%= link_to('Log Out', destroy_user_session_path, method: :delete) %></p>
    <% else %>
      <p> <a> <%= link_to("Log In", user_session_path) %> </a></p>
      <p> <a> <%= link_to("Sign Up", new_user_registration_path) %> </a></p>
    <% end %>
  </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

homework-8/hw8-problem1-app/app/views/users/edit.html.erb
<h1>Edit This User</h1>

<% if @user.errors.any? %>
  <ul>
    <%@user.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <%end %>
   </ul>
 <% end %>

<%= form_for(@user, html: {multipart: true}) do |f| %>

<p>
  <%= f.label(:name) %>:
  <%= f.text_field(:name) %>
</p>

<p>
  <%= f.label(:email) %>:
  <%= f.email_field(:email) %>
</p>

<p>
  <%= f.label(:headline) %>:
  <%= f.text_field(:headline) %>
</p>

<p>
  <%= f.label(:profile) %>:
  <%= f.text_area(:profile) %>
</p>

<p>
<% if current_user.admin? %>
  <%= f.label(:admin) %>
  <%= f.text_area(:admin) %>
<% end %>
</p>

<p> <%= f.submit %></p>

<% end %>

homework-8/hw8-problem1-app/app/views/users/index.html.erb
<h1>All Users</h1>

<div class="user-list">
  <ul>
    <% @users.each do |user| %>
      <li class="user-card">
        <p><%= link_to(user.email, user) %></p>
      </li>
    <% end %>
  </ul>
</div>

homework-8/hw8-problem1-app/app/views/users/show.html.erb
<h1><%= @user.name %> Profile</h1>
<p> Name: <%=@user.name %> </p>
<p> E-mail: <%=@user.email %> </p>
<p> Headline: <%=@user.headline %> </p>
<p> Profile: <%= @user.profile %></p>
<% if current_user.admin? == true %>
  <p> ADMIN: <%=@user.admin %> </p>
<% end %>
<% if (user_signed_in?) && (current_user.admin? || current_user == @user) %>
  <%= link_to('Edit User', edit_user_path) %>
<% else %>
<% end %>